### PR TITLE
bugfix #643: fixed bug with events getting

### LINKED ISSUE #643: Fix bug with events getting
Let's consider ```GET v2/schedule/groups/:groupId/general``` endpoint. 
According to reports from the frontend, it does not work correctly at night or at the end of the week. Most likely, there is bug somewhere in these functions:

image
image

Your task is to find bug and fix it

### PR DESCRIPTION
**Pull request by f-ogoog**
- fixed bug with events getting
- changed unit tests

closes #643

### CODE REVIEW

File: src/v2/api/services/ScheduleService.ts [hunk 1]
```diff
@@ -50,22 +50,22 @@ export class ScheduleService {
...
-        return null;
-      }
-    } else if (period === Period.NO_PERIOD) {
-      return 0;
+  async getIndexOfLesson (week, endOfWeek, event) {
+    const { startDate } = await this.dateService.getCurrentSemester();
+    const startWeek = Math.ceil((event.startTime.getTime() - startDate.getTime()) / WEEK);
+    const endWeek = Math.ceil((event.endTime.getTime() - startDate.getTime()) / WEEK);
+    const difference = endOfWeek.getTime() - event.startTime.getTime();
+    const index = Math.floor(difference / (1000 * 60 * 60 * 24 * 7));
```
Comment (basarabst) [inline src/v2/api/services/ScheduleService.ts:58]: use ```WEEK``` constant

**Review by basarabst — CHANGES_REQUESTED** [review]

**Review by basarabst — APPROVED** [review]
