### PR TITLE
bugfix #455: fixed redundant teacher's role

### LINKED ISSUE #455: Bug with teacher roles on subject
There is a bug when on teacher subject more roles then teacher has.

Example:
image

This teacher doesn't have lecturer role:
opera_IAHgEDC22A

### PR DESCRIPTION
**Pull request by SharpDevOps10**
- used reduce to iterate over array and create new roles
- checked if subjectId of the disciplineTeacher matched the specified subjectId
- checked if role.role is contained in accumulator inside loop
- accumulator returned as final result 

closes #455

### CODE REVIEW

File: src/v2/api/services/TeacherService.ts [hunk 1]
```diff
@@ -243,8 +243,17 @@ export class TeacherService {
     }
 
     const { disciplineTeachers, ...teacher } = dbTeacher;
+    const roles = disciplineTeachers.reduce((acc, disciplineTeacher) => {
```
Comment (basarabst) [inline src/v2/api/services/TeacherService.ts:246]: you can use map instead of reduce

File: src/v2/api/services/TeacherService.ts [hunk 2]
```diff
@@ -243,8 +243,17 @@ export class TeacherService {
...
+      if (disciplineTeacher.discipline.subjectId === subjectId) {
+        disciplineTeacher.roles.forEach((role) => {
+          if (!acc.includes(role.role)) {
+            acc.push(role.role);
```
Comment (basarabst) [inline src/v2/api/services/TeacherService.ts:250]: instead of checking for uniqueness, you can prepare a Set

**Review by basarabst — CHANGES_REQUESTED** [review]

File: src/v2/mappers/DisciplineTeacherMapper.ts [hunk 3]
```diff
@@ -33,4 +33,16 @@ export class DisciplineTeacherMapper {
     }
     return roles;
   }
+
+  getRolesBySubject (disciplineTeachers: DbDisciplineTeacher[], subjectId: string) {
```
Comment (just-hoshinon) [inline src/v2/mappers/DisciplineTeacherMapper.ts:37]: The better solution:
```ts
const roles = [];
for (const dt of disciplineTeachers) {
  if (dt.discipline.subjectId === subjectId) continue;
  roles.push(...dt.roles);
}
return new Set(roles);
```
