### PR TITLE
documentation #818: updated swagger doc for user endpoints:

### LINKED ISSUE #818: Update Swagger doc for User (3)
We are updating the documentation for all endpoints and adding more _description and details_. 

One of the main controllers is User. You should update the documentation according to the **pattern** below:
```ts
  @ApiBearerAuth()
  @ApiOkResponse()
  @ApiBadRequestResponse({
    description: `\n
    InvalidEntityIdException:
      User with such id is not found

    AlreadyRegisteredException:
      User is already registered

    InvalidBodyException:
      Group id can not be empty
      IsCaptain must be a boolean
      IsCaptain can not be empty
    
    AbsenceOfCaptainException:
      Captain was not found
    
    AbsenceOfCaptainTelegramException:
      Captain's telegramId was not found`,
  })
  @ApiUnauthorizedResponse({
    description: `\n
    UnauthorizedException:
      Unauthorized`,
  })
  @ApiForbiddenResponse({
    description: `\n
    NoPermissionException:
      You do not have permission to perform this action
    
    ForbiddenException:
      Forbidden`,
  })
  @ApiParam({
    name: 'userId',
    required: true,
    description: 'Id of a user to request to the group',
  })
  @ApiEndpoint({
    summary: 'Request captain or admin to join the group',
    permissions: PERMISSION.USERS_$USERID_GROUP_REQUEST,
  })
  @Patch('/:userId/requestNewGroup')
  requestNewGroup (
    @Param('userId', UserByIdPipe) userId: string,
    @Body() body: GroupRequestDTO,
  ) {
    return this.userService.requestNewGroup(userId, body);
  }
```
**Structure:**
- auth (if needed)
- ok response
- client errors
- params/query description
- access (if needed)

You should also add **field description** in the bady or response.
Add **summary** to endpoints (fix this issue).
Set **default values** for the optional fields

image

_My DM is always open for you. Happy coding_ 🐸

[Our Swagger](https://apidev.fictadvisor.com/api)
[Doc](https://docs.nestjs.com/openapi/introduction)

### PR DESCRIPTION
**Pull request by aim4ik11**
- POST /v2/users/{userId}/contacts
- PATCH /v2/users/{userId}/contacts/{contactId}
- DELETE /v2/users/{userId}/contacts/{contactId}
- DELETE /v2/users/{userId}/student
- PATCH /v2/users/{userId}/student
- GET /v2/users/{userId}/telegram

closes #818

### CODE REVIEW

File: src/v2/api/controllers/UserController.ts [hunk 1]
```diff
@@ -462,28 +476,69 @@ export class UserController {
...
+  @ApiOkResponse()
+  @ApiParam({
+    name: 'userId',
+    required: true,
+    description: 'Id of a user to delete',
+  })
+  @ApiEndpoint({
+    summary: 'Request captain or admin to delete a student',
+    permissions: PERMISSION.STUDENTS_DELETE,
+  })
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:506]: add InvalidEntityIdException: "User with such id is not found" and UnauthorizedException

File: src/v2/api/controllers/UserController.ts [hunk 2]
```diff
@@ -462,28 +476,69 @@ export class UserController {
...
-  @Access(PERMISSION.USERS_$USERID_CONTACTS_DELETE)
   @Delete('/:userId/contacts/:contactId')
   deleteContact (
-    @Param(ContactByUserIdPipe) params,
+    @Param(ContactByUserIdPipe) params: { userId: string, contactId: string },
   ) {
     return this.userService.deleteContact(params.userId, params.contactId);
   }
 
-  @Access(PERMISSION.STUDENTS_DELETE)
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:478]: add ApiBearerAuth decorator

File: src/v2/api/controllers/UserController.ts [hunk 3]
```diff
@@ -462,28 +476,69 @@ export class UserController {
...
+    permissions: PERMISSION.STUDENTS_DELETE,
+  })
   @Delete('/:userId/student')
   deleteStudent (
     @Param('userId', UserByIdPipe) userId: string,
   ) {
     return this.userService.deleteStudent(userId);
   }
 
-  @Access(PERMISSION.USERS_$USERID_STUDENT_UPDATE)
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:486]: missed ApiBearerAuth decorator

File: src/v2/api/controllers/UserController.ts [hunk 4]
```diff
@@ -462,28 +476,69 @@ export class UserController {
...
+  @ApiOkResponse({
+    type: OrdinaryStudentResponse,
+  })
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:516]: add UnauthorizedException

File: src/v2/api/controllers/UserController.ts [hunk 5]
```diff
@@ -462,28 +476,69 @@ export class UserController {
...
+  @ApiBadRequestResponse({
+    description: `\n
+    InvalidEntityIdException:
+      User with such id is not found
+      
+    InvalidBodyException:
+      First name is not correct (A-Я(укр.)\\-\' )
+      First name is too short (min 2)
+      First name is too long (max 40)
+      Last name of an updated student
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:526]: remove "Last name of an updated student" and unnecessary backslashes (fix your linter)

File: src/v2/api/controllers/UserController.ts [hunk 6]
```diff
@@ -492,7 +547,28 @@ export class UserController {
     return this.userService.updateStudent(userId, body);
   }
 
-  @UseGuards(TelegramGuard)
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:495]: missed ApiBearerAuth decorator

File: src/v2/api/responses/ContactResponse.ts [hunk 7]
```diff
@@ -1,16 +1,24 @@
 import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
 
 export class ContactResponse {
-  @ApiProperty()
+    @ApiProperty({
+      description: 'Id of a contact',
+    })
```
Comment (PavloVlasiuk) [inline src/v2/api/responses/ContactResponse.ts:6]: format this file correctly because you have extra indents

**Review by PavloVlasiuk — CHANGES_REQUESTED** [review]

File: src/v2/api/controllers/UserController.ts [hunk 8]
```diff
@@ -462,28 +474,85 @@ export class UserController {
...
+  @ApiUnauthorizedResponse({
+    description: `\n
+    UnauthorizedException:
+      Unauthorized`,
+  })
+  @ApiBadRequestResponse({
+    description: `\n
+    InvalidEntityIdException:
+      User with such id is not found`,
+  })
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:506]: add @ApiForbiddenResponse with "NoPermissionException: You do not have permission to perform this action"

File: src/v2/api/controllers/UserController.ts [hunk 9]
```diff
@@ -462,28 +474,85 @@ export class UserController {
...
+    InvalidBodyException:
+      First name is not correct (A-Я(укр.)\\-' )
+      First name is too short (min 2)
+      First name is too long (max 40)
+      Last name is not correct (A-Я(укр.)\\-' )
+      Last name is too short (min 2)
+      Last name is too long (max 40)
+      Middle name is not correct (A-Я(укр.)\\-' )
+      Middle name is too long (max 40)`,
+  })
```
Comment (PavloVlasiuk) [inline src/v2/api/controllers/UserController.ts:546]: add NoPermissionException as I have shown above

**Review by PavloVlasiuk — CHANGES_REQUESTED** [review]

**Review by PavloVlasiuk — APPROVED** [review]

File: src/v2/api/controllers/UserController.ts [hunk 10]
```diff
@@ -56,6 +56,7 @@ import { UpdateSuperheroDTO } from '../dtos/UpdateSuperheroDTO';
 import { DisciplineIdsResponse } from '../responses/DisciplineResponse';
 import { SuperheroResponse } from '../responses/SuperheroResponse';
 import { ApiEndpoint } from 'src/v2/utils/documentation/decorators';
+
```
Comment (Dmutre) [inline src/v2/api/controllers/UserController.ts:59]: I can't add it to 148 of code, so I will leave it here. You should move TelegramGuard from ApiEndpoint to UseGuard, because currently TelegramGuard doesn't work with ApiEndpoint. And you should do it to all TelegramGuard in this file

File: src/v2/api/controllers/UserController.ts [hunk 11]
```diff
@@ -56,6 +56,7 @@ import { UpdateSuperheroDTO } from '../dtos/UpdateSuperheroDTO';
...
 @ApiTags('User')
```
Comment (Dmutre) [inline src/v2/api/controllers/UserController.ts:60]: Line 382. It would be better to write 'Id of the role of the user'

File: src/v2/api/controllers/UserController.ts [hunk 12]
```diff
@@ -639,7 +720,29 @@ export class UserController {
     return this.userService.updateStudent(userId, body);
   }
 
-  @UseGuards(TelegramGuard)
+  @ApiBearerAuth()
+  @ApiOkResponse({
+    type: OrdinaryStudentResponse,
+  })
+  @ApiUnauthorizedResponse({
```
Comment (Dmutre) [inline src/v2/api/controllers/UserController.ts:727]: ApiUnauthorizedResponse should go after ApiBadRequestResponse.

File: src/v2/api/controllers/UserController.ts [hunk 13]
```diff
@@ -639,7 +720,29 @@ export class UserController {
...
+      User with such id is not found`,
+  })
+  @ApiParam({
+    name: 'userId',
+    required: true,
+    description: 'Id of a user to get',
+  })
+  @ApiEndpoint({
+    summary: 'Get user by id',
+    guards: TelegramGuard,
```
Comment (Dmutre) [inline src/v2/api/controllers/UserController.ts:744]: Move TelegramGuard to UseGueard.

File: src/v2/api/controllers/UserController.ts [hunk 14]
```diff
@@ -668,7 +771,7 @@ export class UserController {
   @UseGuards(TelegramGuard)
```
Comment (Dmutre) [inline src/v2/api/controllers/UserController.ts:771]: The order isn't correct. It must be ApiBasicAuth, ApiOkResponse,  ApiBadRequestResponse, ApiUnauthorizedResponse, ApiParam, UseGuards. And add ApiEndpoint with summary of endpoint

File: src/v2/api/controllers/UserController.ts [hunk 15]
```diff
@@ -668,7 +771,7 @@ export class UserController {
...
   @Get('/telegramUser/:telegramId')
   async getUserByTelegramId (
-      @Param('telegramId', UserByTelegramIdPipe) telegramId: bigint,
+    @Param('telegramId', UserByTelegramIdPipe) telegramId: bigint,
   ) {
     const student = await this.userService.getUserByTelegramId(telegramId);
     return this.studentMapper.getStudent(student);
```
Comment (Dmutre) [inline src/v2/api/controllers/UserController.ts:777]: Line 780, move Access to ApiEndpoint, add ApiEndpoint with summary. And you should do it to all Access: delete them and move permission to ApiEndpoint

**Review by Dmutre — CHANGES_REQUESTED** [review]

File: src/v2/api/controllers/UserController.ts (hunk 10 above)
Comment (aim4ik11) [reply src/v2/api/controllers/UserController.ts:59]: Not my endpoint

File: src/v2/api/controllers/UserController.ts (hunk 11 above)
Comment (aim4ik11) [reply src/v2/api/controllers/UserController.ts:60]: Not my endpoint

File: src/v2/api/controllers/UserController.ts (hunk 14 above)
Comment (aim4ik11) [reply src/v2/api/controllers/UserController.ts:771]: Not my endpoint

File: src/v2/api/controllers/UserController.ts (hunk 15 above)
Comment (aim4ik11) [reply src/v2/api/controllers/UserController.ts:777]: Not my endpoint

**Review by Dmutre — APPROVED** [review]

File: src/v2/api/responses/ContactResponse.ts [hunk 16]
```diff
@@ -17,7 +17,7 @@ export class ContactResponse {
     displayName: string;
 
   @ApiProperty({
```
Comment (fokaaas) [inline src/v2/api/responses/ContactResponse.ts:19]: Set a default value for link

File: src/v2/api/dtos/CreateContactDTO.ts [hunk 17]
```diff
@@ -22,14 +22,14 @@ export class CreateContactDTO {
...
 
     @ApiProperty({
-      description: 'DisplayName of the contact',
+      description: 'Displayed name of a contact to create',
     })
     @MaxLength(100, validationOptionsMsg('Display name is too long (max: 100)'))
     @IsNotEmpty(validationOptionsMsg('Display name can not be empty'))
       displayName: string;
 
     @ApiPropertyOptional({
```
Comment (fokaaas) [inline src/v2/api/dtos/CreateContactDTO.ts:31]: Set a default value

**Review by fokaaas — CHANGES_REQUESTED** [review]

**Review by fokaaas — APPROVED** [review]
