### PR TITLE
enhancement #680: add weights for permissions during registration

### LINKED ISSUE #680: Add weights for permissions during registration
As you could see recently, information about the weight of each permissions appeared in the database (_grants_ table).

However, there is a problem that during registration they are inserted incorrectly. Your task is to add weight permissions to the logic of formation.

FOR MODERATOR:
image

FOR CAPTAIN:
photo_2023-08-27_00-02-48

All other roles have a default value of 1.

### PR DESCRIPTION
**Pull request by Ksrebniukk**
- added weight permissions

closes #680

### CODE REVIEW

File: src/v2/api/services/GroupService.ts [hunk 1]
```diff
@@ -256,9 +256,10 @@ export class GroupService {
   async addPermissions (groupId: string) {
     for (const { grants, ...roles } of ROLE_LIST) {
 
-      const grantList = Object.entries(grants).map(([permission, set]) => ({
+      const grantList = Object.entries(grants).map(([permission, description]) => ({
         permission: permission.replace('$groupId', groupId),
-        set,
+        set: description.set,
```
Comment (just-hoshinon) [inline src/v2/api/services/GroupService.ts:261]:
``` ts
  set: description.set,
  weight: description.weight,
```
can be simplified to
```ts
  ...description,
```

**Review by just-hoshinon — APPROVED** [review]

**Review by illiakroshka — APPROVED** [review]
