### PR TITLE
documentation #799: updated swagger doc for role endpoints

### LINKED ISSUE #799: Update Swagger doc for Role (1)
We are updating the documentation for all endpoints and adding more _description and details_. 

One of the main controllers is Role. You should update the documentation according to the **pattern** below:
```ts
  @ApiBearerAuth()
  @ApiOkResponse()
  @ApiBadRequestResponse({
    description: `\n
    InvalidEntityIdException:
      User with such id is not found

    AlreadyRegisteredException:
      User is already registered

    InvalidBodyException:
      Group id can not be empty
      IsCaptain must be a boolean
      IsCaptain can not be empty
    
    AbsenceOfCaptainException:
      Captain was not found
    
    AbsenceOfCaptainTelegramException:
      Captain's telegramId was not found`,
  })
  @ApiUnauthorizedResponse({
    description: `\n
    UnauthorizedException:
      Unauthorized`,
  })
  @ApiForbiddenResponse({
    description: `\n
    NoPermissionException:
      You do not have permission to perform this action
    
    ForbiddenException:
      Forbidden`,
  })
  @ApiParam({
    name: 'userId',
    required: true,
    description: 'Id of a user to request to the group',
  })
  @ApiEndpoint({
    summary: 'Request captain or admin to join the group',
    permissions: PERMISSION.USERS_$USERID_GROUP_REQUEST,
  })
  @Patch('/:userId/requestNewGroup')
  requestNewGroup (
    @Param('userId', UserByIdPipe) userId: string,
    @Body() body: GroupRequestDTO,
  ) {
    return this.userService.requestNewGroup(userId, body);
  }
```
**Structure:**
- auth (if needed)
- ok response
- client errors
- params/query description
- api endpoint for summary, permissions, guards

You should also add **field description** in the bady or response.
Add **summary** to endpoints (fix this issue).
Set **default values** for the optional fields

image

**Example**: #777

_My DM is always open for you. Happy coding_ 🐸

[Our Swagger](https://apidev.fictadvisor.com/api)
[Doc](https://docs.nestjs.com/openapi/introduction)

### PR DESCRIPTION
**Pull request by fujivara**
- GET /v2/roles/{roleId}
- DELETE /v2/roles/{roleId}
- PATCH /v2/roles/{roleId}
- GET /v2/roles
- POST /v2/roles

closes #799

### CODE REVIEW

**Review by f-ogoog — APPROVED** [review]

**Review by Yakorrr — APPROVED** [review]

File: src/v2/api/responses/RoleResponse.ts [hunk 1]
```diff
@@ -3,24 +3,35 @@ import { MappedGrant } from './GrantResponse';
...
     weight: number;
 }
 
 export class RoleResponse extends BaseRoleResponse {
-  @ApiProperty({ type: [MappedGrant] })
+  @ApiProperty({
+    type: [MappedGrant],
+    description: 'List of permissions for roles',
+  })
     grants: MappedGrant[];
```
Comment (fokaaas) [inline src/v2/api/responses/RoleResponse.ts:28]: Also add description to MappedGrant

File: src/v2/api/dtos/CreateRoleWithGrantsDTO.ts [hunk 2]
```diff
@@ -7,6 +7,7 @@ import { CreateGrantDTO } from './CreateGrantsDTO';
 export class CreateRoleWithGrantsDTO extends CreateRoleDTO {
   @ApiPropertyOptional({
     type: [CreateGrantDTO],
+    description: 'List of permissions for roles',
   })
   @ValidateNested({ each: true })
   @Type(() => CreateGrantDTO)
```
Comment (fokaaas) [inline src/v2/api/dtos/CreateRoleWithGrantsDTO.ts:13]: Add description to CreateGrantDTO and parentId

**Review by fokaaas — CHANGES_REQUESTED** [review]

**Review by fokaaas — APPROVED** [review]
