### PR TITLE
bugfix #536: fixed rating pagination

### LINKED ISSUE #536: fix rating pagination
There is a bug associated with slow loading of teachers and grades on teacher page. After all, with the increase in the number of teachers, the number of requests increases.

The solution is to add a new column to the teachers table where we will store the teacher rating. Every day at 3 a.m., the rating must be recalculated.

### PR DESCRIPTION
**Pull request by basarabst**
- migration: add_rating_to_teacher
- implemented Cron for rating updating
- added schedule and cron dependencies
- implemented sorting by rating
- changed responses
- removed unused logic

closes #536

### CODE REVIEW

File: src/v2/api/controllers/TeacherController.ts [hunk 1]
```diff
@@ -66,8 +66,8 @@ export class TeacherController {
   async getAll (
     @Query() query: QueryAllTeacherDTO,
   ) {
-    const teachers = await this.teacherService.getAllTeachersWithRating(query);
-    return { teachers: teachers.data, meta: teachers.meta };
+    const teachers = await this.teacherService.getAll(query);
+    return { data: this.teacherMapper.getTeachers(teachers.data), meta: teachers.meta };
```
Comment (just-hoshinon) [inline src/v2/api/controllers/TeacherController.ts:70]: DON'T CHANGE INTERFACE OF ENDPOINT

**Review by just-hoshinon — APPROVED** [review]

File: src/v2/api/controllers/TeacherController.ts (hunk 1 above)
Comment (just-hoshinon) [reply src/v2/api/controllers/TeacherController.ts:70]: 1

**Review by just-hoshinon — CHANGES_REQUESTED** [review]

**Review by just-hoshinon — APPROVED** [review]
