### PR TITLE
enhancement/upgrade-getting-teachers-method

### LINKED ISSUE #287: Upgrading getting teachers for poll
Right now, user can retrieve all discipline teachers that he hasn't answered yet (see example below)

image

But it's not perfect, because there is a number of problems: 
- there is no checking whether it discipline teacher of current semester (as we know, we should not send discipline teachers from current semester) or not
- there is no checking whether this user approved in their group or declined/pending
- there are plenty of code, that do not follow DDD principle (getDisciplineWithTeachers should be a mapper class of returned object from getDisciplines)

Probable solution:
- get current year and semester from the DateService class and filter disciplines
- check user approval of group state and send NoPermissionException 
- create or use mapper class for disciplines, where you put/use a method that properly maps an object (not only disciplinesWithTeachers object, but returning array of objects too)

### PR DESCRIPTION
**Pull request by kropli**
closes #287

### CODE REVIEW

File: src/v2/api/poll/PollService.ts [hunk 1]
```diff
@@ -77,25 +87,24 @@ export class PollService {
       },
     });
 
+    const { semester, year } = await this.dateService.getCurrentSemester();
+
+    disciplines = disciplines.filter(async (discipline) => {
```
Comment (just-hoshinon) [inline src/v2/api/poll/PollService.ts:92]: excessive `async`

File: src/v2/utils/date/DateService.ts [hunk 2]
```diff
@@ -67,4 +71,9 @@ export class DateService {
     const { semester: currentSemester, year: currentYear } = await this.getCurrentSemester();
     return (semester < currentSemester && year === currentYear) || (year < currentYear);
```
Comment (just-hoshinon) [inline src/v2/utils/date/DateService.ts:72]: use method below here

**Review by just-hoshinon — CHANGES_REQUESTED** [review]

**Review by just-hoshinon — APPROVED** [review]
