### PR TITLE
bugfix #719: added check for the existence of captain

### LINKED ISSUE #719: Add check for the existence of captain
When joining group, student must be approved by captain. To do this, we send captain request in Telegram. But it happens that the group doesn't have captain or he doesn't have a telegram id.

image

So if a **regular student** joins a group, you have to throw an exception if they don't have a captain or telegram id.

### PR DESCRIPTION
**Pull request by ArtemLyah**
- added check for existence of captain and captain's telegramId
- added AbsenceOfCaptainTelegramException when captain's telegramId wasn't found

closes #719

### CODE REVIEW

File: src/v2/api/services/AuthService.ts [hunk 1]
```diff
@@ -159,9 +161,12 @@ export class AuthService {
       await this.telegramApi.verifyCaptain(data);
     } else {
       const cap = await this.groupService.getCaptain(groupId);
-      if (cap.telegramId) {
-        await this.telegramApi.verifyStudent({ captainTelegramId: cap.telegramId, ...data });
+      if (!cap) {
```
Comment (f-ogoog) [inline src/v2/api/services/AuthService.ts:164]: maybe rather write one condition and throw one exception?

**Review by f-ogoog — APPROVED** [review]

File: src/v2/api/controllers/UserController.ts [hunk 2]
```diff
@@ -87,12 +87,23 @@ export class UserController {
...
+      IsCaptain can not be empty
+    
+    AbsenceOfCaptainException:
+      Captain was not found
+    
+    AbsenceOfCaptainTelegramException:
+      Captain's telegramId was not found`,
   })
   @ApiForbiddenResponse({
     description: `NoPermissionException:\n
```
Comment (illiakroshka) [inline src/v2/api/controllers/UserController.ts:109]: Add one more ApiForbiddenResponse exeption to swagger 
image
image

**Review by illiakroshka — CHANGES_REQUESTED** [review]

**Review by illiakroshka — APPROVED** [review]

**Review by fokaaas — APPROVED** [review]
