### PR TITLE
bugfix #717: fixed bug with the calculation of the last end date

### LINKED ISSUE #717: Fix bug with the calculation of the last end date
This function does not take into account that there are no pairs for periodic events in last two weeks of the semester. Your task is to add the subtractions of the last two weeks. Also change the latest dates of periodic events in the database.

image

### PR DESCRIPTION
**Pull request by f-ogoog**
- fixed bug with the calculation of the last end date
- changed parsing event info

closes #717

### CODE REVIEW

File: src/v2/api/services/ScheduleService.ts [hunk 1]
```diff
@@ -208,7 +208,7 @@ export class ScheduleService {
   private async getLastEndDate (indexEndDate: Date, period: Period) {
     const { endDate } = await this.dateService.getCurrentSemester();
 
-    const difference = Math.ceil((endDate.getTime() - indexEndDate.getTime()) / DAY);
+    const difference = Math.ceil((endDate.getTime() - (2 * WEEK) - indexEndDate.getTime()) / DAY);
```
Comment (SharpDevOps10) [inline src/v2/api/services/ScheduleService.ts:211]: Use global variable: `FORTNITE`

**Review by SharpDevOps10 — CHANGES_REQUESTED** [review]

**Review by SharpDevOps10 — APPROVED** [review]

**Review by fokaaas — APPROVED** [review]
