### PR TITLE
bugfix #461: fixed adding a contact without link

### LINKED ISSUE #461: bug when adding a contact without link
when adding any contact for a teacher, if you do not enter "link" for example Discord:
image
and sending the request, I get the following error:
image

### PR DESCRIPTION
**Pull request by ArtemLyah**
- set link in contacts as optional

closes #461

### CODE REVIEW

File: src/v2/api/dtos/CreateContactDTO.ts [hunk 1]
```diff
@@ -24,5 +24,6 @@ export class CreateContactDTO {
     @MaxLength(200, validationOptionsMsg('Link is too long (max: 200)'))
     @IsNotEmpty(validationOptionsMsg('Link can not be empty'))
     @IsAscii(validationOptionsMsg('Link contains wrong symbols (ASCII only)'))
-      link: string;
+    @IsOptional()
+      link?: string;
```
Comment (basarabst) [inline src/v2/api/dtos/CreateContactDTO.ts:28]: @IsNotEmpty and @IsOptional decorators contradict each other

**Review by basarabst — CHANGES_REQUESTED** [review]

**Review by basarabst — APPROVED** [review]
