### PR TITLE
bugfix #527: meta comments doesn't work

### LINKED ISSUE #527: Meta comments doesn't work
Request URL - https://apidev.fictadvisor.com/v2/teachers/bf19cf46-9688-47c0-9b13-769ee8cc26b3/comments?page=0&pageSize=5
image

### PR DESCRIPTION
**Pull request by ArtemLyah**
- changed query to questionAnswer in PollService
- added 'totalAmount', 'amount' fields to pagination
- added count method to QuestionAnswerRepository
- changed PollService tests
- created QuestionCommentData
- changed getComments method in QuestionMapper

closes #527

### CODE REVIEW

**Comment by f-ogoog** [comment]
image

you should add enum in ApiPropertyOptional

File: src/v2/api/services/PollService.ts [hunk 1]
```diff
@@ -127,36 +126,55 @@ export class PollService {
...
+      include: undefined,
+    };
+    const questions = await this.questionRepository.findMany((questionsData));
+
+    const commentsData = {
+      where: {
+        disciplineTeacher: {
+          teacherId,
+          discipline: {
+            subjectId: query.subjectId,
```
Comment (SharpDevOps10) [inline src/v2/api/services/PollService.ts:138]: You should throw an exception if `subjectId` is invalid

File: src/v2/api/services/PollService.ts [hunk 2]
```diff
@@ -111,7 +110,7 @@ export class PollService {
     teacherId: string,
     query: CommentsQueryDTO = {}
```
Comment (SharpDevOps10) [inline src/v2/api/services/PollService.ts:111]: Add trailing comma. Also remove unnecessary `= {}`

File: src/v2/api/services/PollService.ts [hunk 3]
```diff
@@ -127,36 +126,55 @@ export class PollService {
...
-              teacherId,
-              discipline: {
-                subjectId: query.subjectId,
-                year: query.year,
-                semester: query.semester,
-              },
-            },
+      include: undefined,
+    };
+    const questions = await this.questionRepository.findMany((questionsData));
```
Comment (SharpDevOps10) [inline src/v2/api/services/PollService.ts:131]: Remove extra brackets

**Review by SharpDevOps10 — CHANGES_REQUESTED** [review]

File: src/v2/api/services/PollService.ts (hunk 2 above)
Comment (ArtemLyah) [reply src/v2/api/services/PollService.ts]: The {} is needed for questionData and commentsData because query.subjectId, query.year, ect will be undefined if query is {}. Otherwise query will be undefined and query.subjectId, query.year, ect won't work

**Review by SharpDevOps10 — APPROVED** [review]

File: src/v2/api/controllers/TeacherController.ts [hunk 4]
```diff
@@ -405,7 +405,7 @@ export class TeacherController {
   }
 
   @ApiOkResponse({
-    type: PaginatedQuestionResponse,
+    type: PaginatedQuestionCommentsResponse,
   })
   @ApiBadRequestResponse({
     description: 'InvalidQueryException',
```
Comment (JessFreak) [inline src/v2/api/controllers/TeacherController.ts:412]: Add /n to string and desribe InvalidQueryExeption with message.

**Review by JessFreak — COMMENTED** [review]
Add checks in CommentsQueryDTO (at least by a number) and describe them

**Review by JessFreak — COMMENTED** [review]
image
merge commits

File: src/v2/api/pipes/CommentsQueryPipe.ts [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+export class CommentsQueryPipe implements PipeTransform {
+  constructor (
+    private subjectRepository: SubjectRepository
+  ) {}
+
+  async transform (query: CommentsQueryDTO) {
+    if (query.subjectId) {
+      const subject = await this.subjectRepository.findById(query.subjectId);
+      if (!subject) {
+        throw new InvalidEntityIdException('subject');
```
Comment (JessFreak) [inline src/v2/api/pipes/CommentsQueryPipe.ts:16]: describe it in the documentation

**Review by SharpDevOps10 — CHANGES_REQUESTED** [review]

**Review by JessFreak — COMMENTED** [review]
image
Use DataNotFoundException

**Review by JessFreak — COMMENTED** [review]
image
image
the text is different

**Review by JessFreak — APPROVED** [review]

**Review by SharpDevOps10 — APPROVED** [review]

**Review by basarabst — APPROVED** [review]
